services:
  docs:
    image: customer_invoices_local_docs
    container_name: customer_invoices_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./customer_invoices:/app/customer_invoices:z
    ports:
      - '9000:9000'
    command: /start-docs
