# Generated by Django 5.0.9 on 2024-09-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_items',
            field=models.IntegerField(default=0),
        ),
    ]
