# Generated by Django 5.0.9 on 2024-09-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_total_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='item',
        ),
        migrations.AddField(
            model_name='invoice',
            name='item',
            field=models.ManyToManyField(to='invoices.item'),
        ),
    ]
